### ISSUE TITLE
Roadmap To 1.0.0

### ISSUE THREAD

**Issue by AldaronLau** [ardaku/alloy#34]
Something like this should/needs be done before a version is released (some more than others, and some might be removed from this list):

 - [ ] Set up Flatpak build - https://github.com/ardaku/alloy/issues/23
 - [x] Rename all cases of emulsion to alloy
 - [x] Fix desktop file https://github.com/ardaku/alloy/issues/13
 - [ ] Fix macOS opening files https://github.com/ardaku/alloy/issues/12
 - [ ] Fix Windows position (https://github.com/ardaku/alloy/issues/30 and https://github.com/ardaku/alloy/issues/29)
 - [ ] Fix zooming (https://github.com/ardaku/alloy/issues/15 and https://github.com/ardaku/alloy/issues/17)
 - [ ] Fix CI https://github.com/ardaku/alloy/issues/35
 - [x] Flatten workspace https://github.com/ardaku/alloy/issues/33
 - [ ] Fix freezing https://github.com/ardaku/alloy/issues/24
 - [x] Fix panic https://github.com/ardaku/alloy/issues/36
 - [ ] Fix choppiness https://github.com/ardaku/alloy/issues/71
 - [x] Fix #208
